### ISSUE TITLE
error if you don't pass the file

### ISSUE THREAD

**Issue by Rub21** [Rub21/geokit#18]
```
Downloads $ geokit filterbyprop --prop tileid=* > fix1.geojson
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at module.exports (/Users/ruben/apps/geokit/src/filterbyprop.js:7:33)
    at Object.<anonymous> (/Users/ruben/apps/geokit/index.js:41:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

It should give us an alert, like `file is missing...`
cc. @karitotp @piligab

**Comment by Rub21** [comment]
Closing this ticket for now!!
